services:
  - type: web
    name: react-metro
    runtime: node
    region: singapore
    plan: free

    buildCommand: |
      npm install
      npm run build
      npm install --prefix server
    startCommand: cd server && npm run start
    envVars:
      - key: SEOUL_METRO_API_KEY
        sync: false

    autoDeploy: true
